apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jessmccreery-hotmail-co-uk/jessnodeproject:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jessmccreery-hotmail-co-uk/jessnodeproject:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jessnodeproject
        chartPath: charts/jessnodeproject
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jessmccreery-hotmail-co-uk/jessnodeproject"
          image.tag: "{{.DIGEST_HEX}}"
